# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.8

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout current
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages

      - name: Cache main
        uses: actions/cache@v2.0.0
        with:
          path: ~/main/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/main/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install main
        run: |
          cd main
          npm ci

      - name: Lint main
        run: |
          cd main
          npm run lint

      # - name: Test main
      #   run: |
      #     cd main
      #     npm test

      - name: Build main
        run: |
          cd main
          npm run build

      - name: Copy main build to gh-pages
        run: |
          cp gh-pages/CNAME CNAME
          rm -rf gh-pages/*
          cp -rf main/public/* gh-pages/
          cp CNAME gh-pages/

      - name: Commit and push GH pages
        run: |
          cd gh-pages
          git config --global user.email "valentin.vago+METAKRONISMS@gmail.com"
          git config --global user.name "Valentin Vago (CI)"
          git status
          git add .
          git commit -m "update site" --allow-empty
          git push
